INSERT INTO themes (text, has_player_var, has_random_player_var, is_predefined, game_id) VALUES

  ('Un nuage avec une forme rigolote', false, false, true, NULL),
  ('La mer vue de dos, sans regarder l objectif', false, false, true, NULL),
  ('Un chemin qui disparait a l horizon', false, false, true, NULL),
  ('Une fleur trouvee par hasard', false, false, true, NULL),
  ('Un arbre impressionnant', false, false, true, NULL),
  ('Le sol sous vos pieds en gros plan', false, false, true, NULL),
  ('La lumiere doree du soir sur votre visage', false, false, true, NULL),
  ('Un ciel d orage ou de gros nuages', false, false, true, NULL),
  ('Un insecte ou petit animal en gros plan', false, false, true, NULL),
  ('L eau en mouvement : vague, fontaine ou robinet', false, false, true, NULL),

  ('Votre serviette de plage posee sur le sable', false, false, true, NULL),
  ('Une terrasse de cafe ou de restaurant', false, false, true, NULL),
  ('Votre creme solaire ou vos lunettes de soleil', false, false, true, NULL),
  ('Un marche local', false, false, true, NULL),
  ('Une vue depuis une hauteur', false, false, true, NULL),
  ('Une enseigne ou pancarte amusante', false, false, true, NULL),
  ('Votre livre ou magazine de vacances', false, false, true, NULL),
  ('Le chemin du retour vers votre hebergement', false, false, true, NULL),
  ('Un bateau, petit ou grand', false, false, true, NULL),
  ('La route vue depuis la voiture', false, false, true, NULL),

  ('Un dessert trop beau pour etre mange', false, false, true, NULL),
  ('Une glace en train de fondre', false, false, true, NULL),
  ('Votre plat du soir en gros plan', false, false, true, NULL),
  ('Un verre avec une belle presentation', false, false, true, NULL),
  ('Le menu d un restaurant local', false, false, true, NULL),
  ('Un snack achete dans la rue', false, false, true, NULL),

  ('Une texture qui vous intrigue : bois, pierre, tissu', false, false, true, NULL),
  ('Quelque chose de bleu dans votre champ de vision', false, false, true, NULL),
  ('Quelque chose de rond', false, false, true, NULL),
  ('Une photo floue intentionnelle', false, false, true, NULL),
  ('Votre ombre sur le sol', false, false, true, NULL),
  ('Un miroir ou une vitre avec un reflet', false, false, true, NULL),
  ('Quelque chose que tout le monde ignore en passant', false, false, true, NULL),
  ('Un detail vu de tres pres', false, false, true, NULL),
  ('Quelque chose de symetrique', false, false, true, NULL),
  ('Une couleur dominante dans votre decor du moment', false, false, true, NULL),

  ('Quelqu un qui regarde au loin', false, false, true, NULL),
  ('Des mains en train de faire quelque chose', false, false, true, NULL),
  ('Quelqu un qui mange les yeux fermes de plaisir', false, false, true, NULL),
  ('Un groupe qui rigole sans savoir qu on les prend en photo', false, false, true, NULL),
  ('Quelqu un de dos face a la mer ou au paysage', false, false, true, NULL),
  ('Des pieds dans le sable ou dans l eau', false, false, true, NULL),

  ('Lumieres de nuit : lampadaires, bougies, guirlandes', false, false, true, NULL),
  ('Le ciel juste apres le coucher de soleil', false, false, true, NULL),
  ('Une photo prise avec seulement la lumiere ambiante', false, false, true, NULL),

  ('Recreez la pose d une statue ou d un personnage peint', false, false, true, NULL),
  ('Un selfie avec quelque chose de ridicule', false, false, true, NULL),
  ('La photo la plus banale possible, rendez-la belle', false, false, true, NULL),
  ('Un objet en equilibre improbable', false, false, true, NULL),
  ('Votre photo la plus artistique du sejour', false, false, true, NULL),
  ('Cachez votre visage avec ce que vous avez autour', false, false, true, NULL),

  ('{player} fait la sieste, vraie ou simulee', true, false, true, NULL),
  ('{player} avec la mer en arriere-plan, les bras grands ouverts', true, false, true, NULL),
  ('{player} goute quelque chose pour la premiere fois', true, false, true, NULL),
  ('{player} fait semblant de soulever un monument', true, false, true, NULL),
  ('{player} rit aux eclats', true, false, true, NULL),
  ('{player} fait la tete ou boude', true, false, true, NULL),
  ('{player} dans sa tenue la plus coloree du sejour', true, false, true, NULL),
  ('{player} fait un saut sur la plage', true, false, true, NULL),
  ('{player} regarde l horizon sans bouger', true, false, true, NULL),
  ('{player} tient un objet comme s il pesait une tonne', true, false, true, NULL),

  ('Surprenez {random_player} sans qu il le sache', false, true, true, NULL),
  ('Faites un calin a {random_player}', false, true, true, NULL),
  ('Imitez la pose de {random_player}', false, true, true, NULL),
  ('{random_player} et vous, les pieds dans l eau', false, true, true, NULL),
  ('Faites une photo floue de {random_player} en mouvement', false, true, true, NULL),
  ('Convainquez {random_player} de faire une grimace', false, true, true, NULL),
  ('{random_player} vous offre quelque chose a manger', false, true, true, NULL),
  ('Photo de dos avec {random_player} face a la mer', false, true, true, NULL);
